# Generated by Django 3.2.19 on 2023-08-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('holding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='customer.holding', verbose_name='holding')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, verbose_name='role name')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
            options={
                'verbose_name': 'User role',
                'verbose_name_plural': 'User roles',
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_companies', to='customer.company', verbose_name='company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'user company',
                'verbose_name_plural': "user's company",
                'ordering': ('company',),
                'unique_together': {('profile', 'company')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_user_role', to='account.userrole', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='OrderItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='template name')),
                ('address', models.TextField(max_length=300, verbose_name='adress')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item_templates_employee', to='customer.employee', verbose_name='responsible person')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item_templates_stock', to='customer.stock', verbose_name='stock')),
                ('user_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item_templates_user_company', to='account.usercompany', verbose_name='user company')),
            ],
            options={
                'verbose_name': 'order item template',
                'verbose_name_plural': 'order item templates',
                'ordering': ('name',),
            },
        ),
    ]
