# Generated by Django 3.2.19 on 2023-07-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item_templates_employee', to='customer.employee', verbose_name='responsible person'),
        ),
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item_templates_stock', to='customer.stock', verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='user_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item_templates_user_company', to='account.usercompany', verbose_name='user company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='customer.holding', verbose_name='holding'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=100, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_companies', to='customer.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='profile'),
        ),
    ]
