# Generated by Django 3.2.19 on 2023-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='template name'),
        ),
    ]
