# Generated by Django 3.2.19 on 2023-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230701_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='address',
            field=models.TextField(max_length=300, verbose_name='adress'),
        ),
    ]
