# Generated by Django 3.2.19 on 2023-07-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_orderitemtemplate_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'ordering': ('company',), 'verbose_name': 'user company', 'verbose_name_plural': "user's company"},
        ),
        migrations.AddField(
            model_name='orderitemtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
