# Generated by Django 3.2.19 on 2023-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usercompany_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, verbose_name='email type name')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
            options={
                'verbose_name': 'User role',
                'verbose_name_plural': 'User roles',
            },
        ),
        migrations.AlterField(
            model_name='orderitemtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
    ]
