# Generated by Django 3.2.19 on 2023-08-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230801_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='date_added',
        ),
    ]
