# Generated by Django 3.2.19 on 2023-08-01 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userrole_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
