# Generated by Django 3.2.19 on 2023-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='role name'),
        ),
    ]
