# Generated by Django 3.2.19 on 2024-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='axial',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='axial'),
        ),
    ]
