# Generated by Django 3.2.19 on 2023-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230720_2131'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_a2070e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_price_3b79b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_descrip_d5da7e_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
