# Generated by Django 3.2.19 on 2023-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentation',
            },
        ),
    ]
