# Generated by Django 3.2.19 on 2023-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_area', '0005_alter_entry_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='content')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Main entry',
                'verbose_name_plural': 'Main entries',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy policy', 'verbose_name_plural': 'Privacy policy'},
        ),
    ]
