# Generated by Django 3.2.19 on 2023-07-01 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('order', 'ORDER')], default='draft', max_length=10, verbose_name='status')),
                ('first_and_last_name', models.CharField(max_length=100, verbose_name='first and last name')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('formed', models.CharField(max_length=100, verbose_name='formed')),
                ('edrpou_code', models.IntegerField()),
                ('address', models.TextField(max_length=200, verbose_name='address')),
                ('services_description', models.TextField(blank=True, max_length=200, verbose_name='services_description')),
                ('comments', models.TextField(blank=True, max_length=200, verbose_name='comments')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=8, verbose_name='rate')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('VIN_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_technique', to='customer.technique', verbose_name='VIN_code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_companies', to='customer.company', verbose_name='company')),
                ('signatory_of_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_employees', to='customer.employee', verbose_name='signatory_of_documents')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_stocks', to='customer.stock', verbose_name='stock')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_templates', to='account.orderitemtemplate', verbose_name='template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_quantity', models.PositiveIntegerField(default=1)),
                ('ord_quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
