# Generated by Django 3.2.19 on 2023-07-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('customer', '0001_initial'),
        ('orders', '0002_alter_order_edrpou_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='VIN_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_technique', to='customer.technique', verbose_name='VIN code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='services description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='signatory_of_documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_employees', to='customer.employee', verbose_name='signatory of documents'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ord_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='order quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pre_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='pre quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='product'),
        ),
    ]
